pipeline {
    agent any
    environment {
      APPNAME = 'PATIENTS'
      APPDIR = 'automation-framework-demo'
      ANSIBLE_DIR = "$APPDIR/ansible"
    }
    stages {
        stage('Prepare Environment'){
            steps {
                sh "env"
                sh "git clean -ffdx"
                sh "echo $PATH"
            }
        }

        stage('Compile Application') {
            steps {
                dir (env.ANSIBLE_DIR) {
                    sh "echo Compile"
                    sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x -e sdlc_env=LOCAL --tags \"build\" --limit localhost"
                }
            }
        }

        stage('Package and Test SQL Changes') {
			steps {
                echo "Package and Test SQL Changes"
			} 
        }

        stage('Deploy Application Stack') {
            steps {
                dir (env.ANSIBLE_DIR) {
                // sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x -e sdlc_env=DEV --tags \"deploy\" --limit devweb"
                sh "echo Deploy"
                }
            }
        }
    }
}
 