pipeline {
    agent any
    environment {
      APPNAME = 'PATIENTS'
    }
    stages {
        stage('Prepare Environment'){
            steps {
                sh "env"
                sh "git clean -ffdx"
                sh "echo $PATH"
            }
        }

        stage('Compile Application') {
            steps {
                dir ('ansible') {
                    // sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x sdlc_env=DEV --tags \"build\" --limit devweb"
                    sh "echo Compile"
                }
            }
        }

        stage('Package and Test SQL Changes') {
			steps {
                echo "Package and Test SQL Changes"
			} 
        }

        stage('Deploy Application Stack') {
            steps {
                dir ('ansible') {
                // sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x sdlc_env=DEV --tags \"deploy\" --limit devweb"
                sh "echo Deploy"
                }
            }
        }
    }
}
 