pipeline {
    agent any
    environment {
      APPNAME = 'PATIENTS'
      APPDIR = 'automation-framework-demo'
      ANSIBLE_DIR = "$APPDIR/ansible"
      TITAN = '/usr/local/bin/titan'
      JAR = 'postgresql.jar'
      PG_CONTAINERNAME = 'patients-db'
      JQ = 'docker run -i stedolan/jq'
      LIQUIBASE = 'docker run -v /var/lib/jenkins/jdbc:/liquibase/jdbc -v $(pwd)/changelog:/liquibase/changelog liquibase/liquibase --driver=org.postgresql.Driver --classpath=/liquibase/jdbc/${JAR} --url="jdbc:postgresql://$IPADDRESS:5432/dafdb" --changeLogFile=/liquibase/changelog/changelog.yaml --username=delphixdb --password=delphixdb'
    }
    stages {
        stage('Prepare Environment'){
            steps {
                sh "env"
                sh "git clean -ffdx"
                sh "echo $PATH"
                sh "chmod a+w changelog"
            }
        }

        stage('Compile Application') {
            steps {
                dir (env.ANSIBLE_DIR) {
                    sh "echo Compile"
                    // sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x -e sdlc_env=LOCAL --tags \"build\" --limit localhost"
                }
            }
        }

        stage('Database') {
			steps {
                sh """
                    echo "Titan-y things"
                    echo ${PG_CONTAINERNAME}
                    ${TITAN} checkout -t prod ${PG_CONTAINERNAME}
                    sleep 5
                    IPADDRESS=\$(docker network inspect bridge | jq -r '.[].Containers[]|select(.Name=="'${PG_CONTAINERNAME}'")|.IPv4Address| split("/")|.[0]')
                    ${LIQUIBASE} validate
                    ${LIQUIBASE} updateSQL
                    ${LIQUIBASE} update
                """
			} 
        }

        stage('Deploy Application Stack') {
            steps {
                dir (env.ANSIBLE_DIR) {
                    sh "echo Deploy"
                    // sh  "ansible-playbook deploy.yaml -e git_branch=origin/develop -e git_commit=x -e sdlc_env=LOCAL --tags \"deploy\" --limit localhost"
                }
            }
        }
    }
}
 